services:
  app:
    build:
      context: ./
    ports:
      - "7008:7008"
    restart: unless-stopped
    init: true
    depends_on:
      - db
    networks:
      - app_network
  scripts:
    build:
      context: ./scripts
    restart: unless-stopped
    init: true
    networks:
      - app_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  db_data:
networks:
  app_network: