version: '3.8'

services:
  js-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: js-client
    restart: unless-stopped
    networks:
      - appnet
    ports:
      - "3003:3003" # Next.js client

  js-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: js-server
    restart: unless-stopped
    init: true
    networks:
      - appnet
    ports:
      - "7008:7008" # Main server port
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: admin # Set as needed
      POSTGRES_PASSWORD: password # Set as needed

  ts-ceramic-mcp-app:
    build:
      context: .
      dockerfile: ./server/ceramic-mcp/ceramic-app-app.Dockerfile
    container_name: ts-ceramic-mcp-app
    restart: unless-stopped
    init: true
    networks:
      - appnet
    ports:
      - "3001:3002" # Expose on 3001 to avoid conflict with client

  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: postgres
    restart: unless-stopped
    networks:
      - appnet
    ports:
      - "5432:5433" # Expose if you want to connect externally
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local

networks:
  appnet:
    driver: bridge
