ignoredBuiltDependencies:
  - "@scarf/scarf"
  - aws-sdk
  - better-sqlite3
  - bufferutil
  - classic-level
  - go-ipfs
  - keccak
  - protobufjs
  - secp256k1
  - sqlite3
  - tiny-secp256k1
  - utf-8-validate
onlyBuiltDependencies:
  - "@ipshipyard/node-datachannel"
