version: "3.8"
services:
  ts-ceramic-mcp-app:
    build:
      context: server/ceramic-mcp
      dockerfile: /ceramic-app-app.Dockerfile
    container_name: ts-ceramic-mcp-app
    restart: unless-stopped
    init: true
    networks:
      - appnet
    ports:
      - "3001:3000" # Expose on 3001 to avoid conflict with client

  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: postgres
    restart: unless-stopped
    networks:
      - appnet
    ports:
      - "5432:5432" # Expose if you want to connect externally
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local

networks:
  appnet:
    driver: bridge
