{
  "anchor": { "auth-method": "did" },
  "http-api": { "cors-allowed-origins": [".*"], "admin-dids": [] },
  "ipfs":
    {
      "mode": "remote",
      "host": "http://localhost:5101",
      "disable-peer-data-sync": false,
    },
  "logger": { "log-level": 2, "log-to-files": false },
  "metrics":
    { "metrics-exporter-enabled": false, "metrics-publisher-enabled": true },
  "network": { "name": "testnet-clay" },
  "node":
    {
      "privateSeedUrl": "inplace:ed25519#086c74acc689204865fae66d5102a9595591ae74ef768004284d18ae41275958",
    },
  "state-store":
    {
      "mode": "fs",
      "local-directory": "/Users/jeldonmusic/.ceramic/statestore/",
    },
  "indexing":
    {
      "db": "sqlite:///Users/jeldonmusic/.ceramic/indexing.sqlite",
      "allow-queries-before-historical-sync": true,
      "disable-composedb": false,
      "enable-historical-sync": false,
    },
}
